decidim-core/config/routes.rb
# frozen_string_literal: true

Decidim::Core::Engine.routes.draw do
  mount Decidim::Api::Engine => "/api"

  devise_for :users,
             class_name: "Decidim::User",
             module: :devise,
             router_name: :decidim,
             controllers: {
               invitations: "decidim/devise/invitations",
               sessions: "decidim/devise/sessions",
               confirmations: "decidim/devise/confirmations",
               registrations: "decidim/devise/registrations",
               passwords: "decidim/devise/passwords",
               omniauth_callbacks: "decidim/devise/omniauth_registrations"
             }

  devise_scope :user do
    post "omniauth_registrations" => "devise/omniauth_registrations#create"
  end

  resource :locale, only: [:create]

  Decidim.participatory_space_manifests.each do |manifest|
    mount manifest.engine, at: "/", as: "decidim_#{manifest.name}"
  end

  authenticate(:user) do
    resources :authorizations, only: [:new, :create, :index] do
      collection do
        get :first_login
      end
    end
    resource :account, only: [:show, :update, :destroy], controller: "account" do
      member do
        get :delete
      end
    end
    resources :notifications, only: [:index, :destroy] do
      collection do
        delete :read_all
      end
    end
    resource :notifications_settings, only: [:show, :update], controller: "notifications_settings"
    resources :own_user_groups, only: [:index]
  end

  resources :pages, only: [:index, :show], format: false

  get "/scopes/search", to: "scopes#search", as: :scopes_search

  get "/static_map", to: "static_map#show", as: :static_map
  get "/cookies/accept", to: "cookie_policy#accept", as: :accept_cookies

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resource :follow, only: [:create, :destroy]
  resource :report, only: [:create]

  root to: "pages#show", id: "home"
end

decidim-core/app/models/decidim/abilities/admin_ability.rb
# frozen_string_literal: true

module Decidim
  module Abilities
    # Defines the abilities for an admin user. Intended to be used with `cancancan`.
    class AdminAbility
      include CanCan::Ability

      attr_reader :user

      def initialize(user, context)
        @user = user
        @context = context

        define_abilities if admin?
      end

      def define_abilities
        can :read, :admin_dashboard
        can :read, Feature
        can :impersonate, :managed_users
      end

      def admin?
        @user && @user.admin?
      end
    end
  end
end

decidim-core/app/models/decidim/abilities/base_ability.rb
# frozen_string_literal: true

module Decidim
  module Abilities
    # Defines the abilities for a User. Intended to be used with `cancancan`.
    class BaseAbility
      include CanCan::Ability

      # Initializes the ability class for the given user. Automatically merges
      # injected abilities fmor the configuration. In order to inject more
      # abilities, add this code in the `engine.rb` file of your own engine, for
      # example, inside an initializer:
      #
      #   Decidim.configure do |config|
      #     config.abilities << Decidim::MyEngine::Abilities::MyAbility
      #   end
      #
      # Note that, in development, this will force you to restart the server
      # every time you change things in your ability classes.
      #
      # user - the User that needs its abilities checked.
      # context - a Hash with some context related to the current request.
      def initialize(user, context = {})
        Decidim.abilities.each do |ability|
          merge ability.constantize.new(user, context)
        end

        can :manage, Authorization do |authorization|
          authorization.user == user
        end

        can :manage, Follow do |follow|
          follow.user == user
        end

        can :manage, Notification do |notification|
          notification.user == user
        end
      end
    end
  end
end

decidim-core/app/models/decidim/abilities/everyone_ability.rb
# frozen_string_literal: true

module Decidim
  module Abilities
    # Defines the base abilities for any user. Guest users will use these too.
    # Intended to be used with `cancancan`.
    class EveryoneAbility
      include CanCan::Ability

      def initialize(user, _context)
        can :read, :public_pages
        can :manage, :locales

        can :read, Feature, &:published?

        can :search, Scope

        can :manage, User do |other|
          other == user
        end
      end
    end
  end
end

decidim-core/app/models/decidim/abilities/participatory_process_admin_ability.rb
# frozen_string_literal: true

module Decidim
  module Abilities
    # Defines the abilities for a participatory process admin. Intended to be
    # used with `cancancan`.
    # This ability will not apply to organization admins.
    class ParticipatoryProcessAdminAbility < ParticipatoryProcessRoleAbility
      # Overrides ParticipatoryProcessRoleAbility role method
      def role
        :admin
      end

      # Overrides ParticipatoryProcessRoleAbility define_participatory_process_abilities method
      def define_participatory_process_abilities
        super

        can :read, ParticipatoryProcess do |process|
          can_manage_process?(process)
        end

        can :read, Feature do |feature|
          can_manage_process?(feature.participatory_space)
        end
      end
    end
  end
end

decidim-core/app/models/decidim/abilities/participatory_process_collaborator_ability.rb
# frozen_string_literal: true

module Decidim
  module Abilities
    # Defines the abilities for a participatory process collaborator. Intended to be
    # used with `cancancan`.
    # This ability will not apply to organization admins.
    class ParticipatoryProcessCollaboratorAbility < ParticipatoryProcessRoleAbility
      # Overrides ParticipatoryProcessRoleAbility role method
      def role
        :collaborator
      end

      # Overrides ParticipatoryProcessRoleAbility define_participatory_process_abilities method
      def define_participatory_process_abilities
        super

        can :read, ParticipatoryProcess do |process|
          can_manage_process?(process)
        end

        can :read, Feature do |feature|
          can_manage_process?(feature.participatory_space)
        end
      end
    end
  end
end

decidim-core/app/models/decidim/abilities/participatory_process_moderator_ability.rb
# frozen_string_literal: true

module Decidim
  module Abilities
    # Defines the abilities for a participatory process moderator. Intended to be
    # used with `cancancan`.
    # This ability will not apply to organization admins.
    class ParticipatoryProcessModeratorAbility < ParticipatoryProcessRoleAbility
      # Overrides ParticipatoryProcessRoleAbility role method
      def role
        :moderator
      end
    end
  end
end

decidim-core/app/models/decidim/abilities/user_manager_ability.rb
# frozen_string_literal: true

module Decidim
  module Abilities
    # Defines the abilities for an user with role 'user_manager'.
    # Intended to be used with `cancancan`.
    class UserManagerAbility
      include CanCan::Ability

      attr_reader :user

      def initialize(user, context)
        @user = user
        @context = context

        define_abilities if not_admin? && user_manager?
      end

      def define_abilities
        can :read, :admin_dashboard
        can :impersonate, :managed_users
      end

      # Whether the user is an admin or not.
      def not_admin?
        @user && !@user.admin?
      end

      # Whether the user has the user_manager role or not.
      def user_manager?
        @user.role? "user_manager"
      end
    end
  end
end

decidim-core/app/models/decidim/application_record.rb
# frozen_string_literal: true

module Decidim
  # Main ActiveRecord application configuration.
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

decidim-core/app/models/decidim/attachment.rb
# frozen_string_literal: true

module Decidim
  # Attachment can be any type of document or images related to a partcipatory
  # process.
  class Attachment < ApplicationRecord
    belongs_to :attached_to, polymorphic: true

    validates :file, :content_type, presence: true
    validates :file, file_size: { less_than_or_equal_to: ->(_attachment) { Decidim.maximum_attachment_size } }
    mount_uploader :file, Decidim::AttachmentUploader

    # Whether this attachment is a photo or not.
    #
    # Returns Boolean.
    def photo?
      @photo ||= content_type.start_with? "image"
    end

    # Whether this attachment is a document or not.
    #
    # Returns Boolean.
    def document?
      !photo?
    end

    # Which kind of file this is.
    #
    # Returns String.
    def file_type
      file.url&.split(".")&.last&.downcase
    end

    # The URL to download the file.
    #
    # Returns String.
    delegate :url, to: :file

    # The URL to download the thumbnail of the file. Only works with images.
    #
    # Returns String.
    def thumbnail_url
      return unless photo?
      file.thumbnail.url
    end

    # The URL to download the a big version of the file. Only works with images.
    #
    # Returns String.
    def big_url
      return unless photo?
      file.big.url
    end
  end
end

decidim-core/app/models/decidim/authorization.rb
# frozen_string_literal: true

module Decidim
  # An authorization is a record that a User has been authorized somehow. Other
  # models in the system can use different kind of authorizations to allow a
  # user to perform actions.
  #
  # To create an authorization for a user we need to use an
  # AuthorizationHandler that validates the user against a set of rules. An
  # example could be a handler that validates a user email against an API and
  # depending on the response it allows the creation of the authorization or
  # not.
  class Authorization < ApplicationRecord
    belongs_to :user, foreign_key: "decidim_user_id", class_name: "Decidim::User", inverse_of: :authorizations

    validates :name, uniqueness: { scope: :decidim_user_id }

    validate :active_handler?

    private

    def active_handler?
      AuthorizationHandler.active_handler?(name)
    end
  end
end

decidim-core/app/models/decidim/categorization.rb
# frozen_string_literal: true

module Decidim
  class Categorization < ApplicationRecord
    belongs_to :category, foreign_key: :decidim_category_id
    belongs_to :categorizable, polymorphic: true
  end
end

decidim-core/app/models/decidim/category.rb
# frozen_string_literal: true

module Decidim
  # Categories serve as a taxonomy for components to use for while in the
  # context of a participatory process.
  class Category < ApplicationRecord
    belongs_to :participatory_space, foreign_key: "decidim_participatory_space_id", foreign_type: "decidim_participatory_space_type", polymorphic: true
    has_many :subcategories, foreign_key: "parent_id", class_name: "Decidim::Category", dependent: :destroy, inverse_of: :parent
    belongs_to :parent, class_name: "Decidim::Category", foreign_key: "parent_id", inverse_of: :subcategories, optional: true
    has_many :categorizations, foreign_key: "decidim_category_id", class_name: "Decidim::Categorization", dependent: :destroy

    validate :forbid_deep_nesting
    before_validation :subcategories_have_same_participatory_space

    # Scope to return only the first-class categories, that is, those that are
    # not subcategories.
    #
    # Returns an ActiveRecord::Relation.
    def self.first_class
      where(parent_id: nil)
    end

    def unused?
      categorizations.empty?
    end

    private

    def forbid_deep_nesting
      return unless parent
      return if parent.parent.blank?

      errors.add(:parent_id, :nesting_too_deep)
    end

    def subcategories_have_same_participatory_space
      return unless parent
      self.participatory_space = parent.participatory_space
    end
  end
end

decidim-core/app/models/decidim/feature.rb
# frozen_string_literal: true

module Decidim
  # A Feature represents a self-contained group of functionalities usually
  # defined via a FeatureManifest. It's meant to be able to provide a single
  # feature that spans over several steps.
  class Feature < ApplicationRecord
    include HasSettings
    include Publicable

    belongs_to :participatory_space, polymorphic: true

    default_scope { order(arel_table[:weight].asc) }

    delegate :organization, :categories, to: :participatory_space
    delegate :scopes, to: :organization

    # Public: Finds the manifest this feature is associated to.
    #
    # Returns a FeatureManifest.
    def manifest
      Decidim.find_feature_manifest(manifest_name)
    end

    # Public: Assigns a manifest to this feature.
    #
    # manifest - The FeatureManifest for this Feature.
    #
    # Returns nothing.
    def manifest=(manifest)
      self.manifest_name = manifest.name
    end

    # Public: The name of the engine the feature is mounted to.
    def mounted_engine
      "decidim_#{participatory_space_name}_#{manifest_name}"
    end

    # Public: The name of the admin engine the feature is mounted to.
    def mounted_admin_engine
      "decidim_admin_#{participatory_space_name}_#{manifest_name}"
    end

    # Public: The hash of contextual params when the feature is mounted.
    def mounted_params
      {
        host: organization.host,
        feature_id: id,
        "#{participatory_space.underscored_name}_slug".to_sym => participatory_space.slug
      }
    end

    # Public: Returns the value of the registered primary stat.
    def primary_stat
      @primary_stat ||= manifest.stats.filter(primary: true).with_context([self]).map { |name, value| [name, value] }.first&.last
    end

    private

    def participatory_space_name
      participatory_space.underscored_name
    end
  end
end

decidim-core/app/models/decidim/follow.rb
# frozen_string_literal: true

module Decidim
  class Follow < ApplicationRecord
    belongs_to :followable, foreign_key: "decidim_followable_id", foreign_type: "decidim_followable_type", polymorphic: true
    belongs_to :user, foreign_key: "decidim_user_id", class_name: "Decidim::User"

    validates :user, uniqueness: { scope: [:followable] }
  end
end

decidim-core/app/models/decidim/identity.rb
# frozen_string_literal: true

module Decidim
  # Store user's social identities
  class Identity < ApplicationRecord
    belongs_to :user, foreign_key: :decidim_user_id, class_name: "Decidim::User"
    belongs_to :organization, foreign_key: :decidim_organization_id, class_name: "Decidim::Organization"

    validates :provider, presence: true
    validates :uid, presence: true, uniqueness: { scope: [:provider, :organization] }

    validate :same_organization

    private

    def same_organization
      return if organization == user&.organization
      errors.add(:organization, :invalid)
    end
  end
end

decidim-core/app/models/decidim/impersonation_log.rb
# frozen_string_literal: true

module Decidim
  # ImpersonationLogs are created whenever an admin impersonate a managed user
  class ImpersonationLog < ApplicationRecord
    SESSION_TIME_IN_MINUTES = 30

    belongs_to :admin, foreign_key: "decidim_admin_id", class_name: "Decidim::User"
    belongs_to :user, foreign_key: "decidim_user_id", class_name: "Decidim::User"

    validate :same_organization, :non_active_impersonation

    scope :active, -> { where(ended_at: nil) }

    def ended?
      ended_at.present?
    end

    def expired?
      expired_at.present?
    end

    private

    def same_organization
      return if admin&.organization == user&.organization
      errors.add(:admin, :invalid)
    end

    def non_active_impersonation
      return if ended? || expired?
      errors.add(:admin, :invalid) if Decidim::ImpersonationLog.where(admin: admin).active.any?
    end
  end
end

decidim-core/app/models/decidim/moderation.rb
# frozen_string_literal: true

module Decidim
  # A moderation belongs to a reportable and includes many reports
  class Moderation < ApplicationRecord
    belongs_to :reportable, foreign_key: "decidim_reportable_id", foreign_type: "decidim_reportable_type", polymorphic: true
    belongs_to :participatory_space, foreign_key: "decidim_participatory_space_id", foreign_type: "decidim_participatory_space_type", polymorphic: true
    has_many :reports, foreign_key: "decidim_moderation_id", class_name: "Decidim::Report"

    delegate :feature, :organization, to: :reportable

    def authorized?
      upstream_moderation == "authorized"
    end

    def unmoderated?
      upstream_moderation == "unmoderate"
    end

    def authorize!
      update_attributes(upstream_moderation: "authorized")
      reportable.send_notification if reportable.class.name.demodulize == "Comment"
    end

    def refuse!
      update_attributes(upstream_moderation: "refused")
    end

    def upstream_activated?
      if reportable.is_a?(Decidim::Proposals::Proposal)
        reportable.feature.settings.upstream_moderation_enabled
      else
        reportable.root_commentable.feature.settings.comments_upstream_moderation_enabled
      end
    end
  end
end

decidim-core/app/models/decidim/notification.rb
# frozen_string_literal: true

module Decidim
  class Notification < ApplicationRecord
    belongs_to :resource, foreign_key: "decidim_resource_id", foreign_type: "decidim_resource_type", polymorphic: true
    belongs_to :user, foreign_key: "decidim_user_id", class_name: "Decidim::User"

    def event_class_instance
      @event_class_instance ||= event_class.constantize.new(resource: resource, event_name: event_name, user: user, extra: extra)
    end
  end
end

decidim-core/app/views/layouts/decidim/_application.html.erb
<% add_decidim_meta_tags({
  description: strip_tags(translated_attribute(current_organization.description)),
  title: current_organization.name,
  url: request.original_url,
  twitter_handler: current_organization.twitter_handler,
  image_url: current_organization.homepage_image.url
}) %>

<!DOCTYPE html>
<html lang="<%= I18n.locale %>" class="no-js">
  <head>
    <title><%= decidim_page_title %></title>
    <%= render partial: 'layouts/decidim/head' %>
  </head>

  <body>
    <%= render partial: 'layouts/decidim/impersonation_warning' %>
    <%= render partial: 'layouts/decidim/cookie_warning' %>

    <%= render 'layouts/decidim/wrapper' do %>
      <%= yield %>
    <% end %>

    <%= render partial: "decidim/shared/login_modal" %>
  </body>
</html>

decidim-core/app/views/layouts/decidim/_cookie_warning.html.erb
<% unless cookies_accepted? %>
  <div class="cookie-warning">
    <%= t('.description_html', link: link_to(t('.link_label'), decidim.page_path('terms-and-conditions'), target: "_blank")) %>
    <div class="cookie-warning__action">
      <%= button_to t('.ok'), decidim.accept_cookies_path, method: :get, remote: true, class: "button tiny cookie-bar__button" %>
    </div>
  </div>
<% end %>

decidim-core/app/views/layouts/decidim/_head.html.erb
<%= csrf_meta_tags %>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<% available_locales.each do |locale| %>
  <link rel="alternate" href="<%= url_for(request.parameters.merge(locale: locale)) %>" hreflang="<%= locale %>" />
<% end %>

<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:site" content="@<%= decidim_meta_twitter_handler %>" />
<meta name="twitter:title" content="<%= decidim_page_title %>" />
<meta name="twitter:description" content="<%= decidim_meta_description %>" />
<meta name="twitter:image" content="<%= decidim_meta_image_url %>" />

<meta property="og:url" content="<%= decidim_meta_url %>" />
<meta property="og:type" content="article" />
<meta property="og:title" content="<%= decidim_page_title %>" />
<meta property="og:description" content="<%= decidim_meta_description %>" />
<meta property="og:image" content="<%= decidim_meta_image_url %>" />

<%= favicon %>
<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>

<%= render partial: 'layouts/decidim/head_extra' %>
<%== current_organization.header_snippets if Decidim.enable_html_header_snippets %>

decidim-core/app/views/layouts/decidim/_head_extra.html.erb
<%#
This file is meant to be overriden by the app developers in order to
include extra headers like tracking, error handling and such.

Note that thie code you add here will be run for all organizations in
your instance of Decidim. If you want to add code for a specific
organization, add it to the organization's `header_snippets` field,
which can be modified at the organization admin section.

The `header_snippets` organization field will render *after* this file.

Just copy your own version of the file under:
`app/views/layouts/decidim/_head_extra.html.erb`
%>

decidim-core/app/views/layouts/decidim/_impersonation_warning.html.erb
<% if current_user&.managed? %>
  <div class="impersonation-warning" data-session-ends-at="<%= impersonation_session_ends_at.iso8601 %>">
    <%= t('.description_html', user_name: current_user.name) %>
    <%= t('.expire_time_html', minutes: impersonation_session_remaining_duration_in_minutes) %>
    <div class="impersonation-warning__action">
      <%= button_to t('.close_session'), decidim_admin.close_session_managed_user_impersonations_path(current_user), class: "button tiny impersonation-bar__button" %>
    </div>
  </div>
  <%= javascript_include_tag "decidim/impersonation" %>
<% end %>

decidim-core/app/views/layouts/decidim/_language_chooser.html.erb
<% if available_locales.length > 1 %>
  <div class="topbar__dropmenu language-choose">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="is-dropdown-submenu-parent">
        <%= link_to t("name", scope: "locale") %>
        <ul class="menu is-dropdown-submenu">
          <% (available_locales - [I18n.locale.to_s]).each do |locale| %>
            <li><%= link_to locale_name(locale), decidim.locale_path(locale: locale), method: :post%></li>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
<% end %>

decidim-core/app/views/layouts/decidim/_logo.html.erb
<% if organization %>
  <%= link_to decidim.root_url(host: organization.host) do %>
    <% if organization.logo.present? %>
      <%= image_tag organization.logo.medium.url %>
    <% else %>
      <span><%= organization.name %></span>
      <style>
       .logo-wrapper span{
         color: white;
         font-weight: 600;
         font-size: 1.4em;
         display: inline-block;
         text-align: left;
         padding-left: 8px;
         line-height: 1;
         position: relative;
       }
       .logo-wrapper span:before{
         content: "";
         display: block;
         position: absolute;
         border-left: 4px solid white;
         height: 88%;
         top: 6%; left: 0;
       }
      </style>
    <% end %>
  <% end %>
<% else %>
  <%= Decidim.application_name %>
<% end %>

decidim-core/app/views/layouts/decidim/_mailer_logo.html.erb
<% if organization %>
  <%= link_to decidim.root_url(host: organization.host) do %>
    <% if organization.logo.present? %>
      <%= image_tag organization.logo.medium.url, style: "max-height: 50px", alt: "" %>
    <% else %>
      <span><%= organization.name %></span>
      <style>
       .logo-wrapper span{
         color: white;
         font-weight: 600;
         font-size: 1.4em;
         display: inline-block;
         text-align: left;
         padding-left: 8px;
         line-height: 1;
         position: relative;
       }
       .logo-wrapper span:before{
         content: "";
         display: block;
         position: absolute;
         border-left: 4px solid white;
         height: 88%;
         top: 6%; left: 0;
       }
      </style>
    <% end %>
  <% end %>
<% else %>
  <%= Decidim.application_name %>
<% end %>

decidim-core/app/views/layouts/decidim/_social_media_links.html.erb
<div class="medium-4 large-3 column main__footer__social">
  <ul class="footer-social">
    <% if current_organization.twitter_handler.present? %>
      <li>
        <a class="footer-social__icon" target="_blank" title="Twitter" href="https://twitter.com/<%= current_organization.twitter_handler %>">
          <%= icon 'twitter', role: 'img', aria_label: 'Twitter' %>
        </a>
      </li>
    <% end %>
    <% if current_organization.facebook_handler.present? %>
      <li>
        <a class="footer-social__icon" target="_blank" title="Facebook" href="https://www.facebook.com/<%= current_organization.facebook_handler %>">
          <%= icon 'facebook', role: 'img', aria_label: 'Facebook' %>
        </a>
      </li>
    <% end %>
    <% if current_organization.instagram_handler.present? %>
      <li>
        <a class="footer-social__icon" target="_blank" title="Instagram" href="https://www.instagram.com/<%= current_organization.instagram_handler %>">
          <%= icon 'instagram', role: 'img', aria_label: 'Instagram' %>
        </a>
      </li>
    <% end %>
    <% if current_organization.youtube_handler.present? %>
      <li>
        <a class="footer-social__icon" target="_blank" title="YouTube" href="https://www.youtube.com/<%= current_organization.youtube_handler %>">
          <%= icon 'youtube', role: 'img', aria_label: 'YouTube' %>
        </a>
      </li>
    <% end %>
    <% if current_organization.github_handler.present? %>
      <li>
        <a class="footer-social__icon" target="_blank" title="GitHub" href="https://www.github.com/<%= current_organization.github_handler %>">
          <%= icon 'github', role: 'img', aria_label: 'GitHub' %>
        </a>
      </li>
    <% end %>
  </ul>
</div>

decidim-core/app/views/layouts/decidim/_user_menu.html.erb
<li><%= link_to t(".profile"), decidim.account_path %></li>
<li><%= link_to t(".notifications"), decidim.notifications_path %></li>
<% if can? :read, :admin_dashboard %>
  <li><%= link_to t(".admin_dashboard"), decidim_admin.root_path %></li>
<% end %>
<li><%= link_to t(".sign_out"), decidim.destroy_user_session_path, method: :delete, class: "sign-out-link" %></li>

decidim-core/app/views/layouts/decidim/application.html.erb
<%= render "layouts/decidim/application" do %>
  <%= yield %>
<% end %>

decidim-core/app/views/layouts/decidim/user_profile.html.erb
<%= render "layouts/decidim/application" do %>
  <main class="wrapper">
    <div class="row collapse">
      <div class="columns">
        <h1 class="heading1 user-header"><%= t("title", scope: "layouts.decidim.user_profile") %></h1>
      </div>
    </div>
    <div class="row collapse">
      <div class="main-container">
        <div class="row collapse main-container--side-panel">
          <div class="columns medium-4 large-3">
            <div class="side-panel">
              <ul class="tabs vertical side-panel__tabs" id="user-settings-tabs">
                <%= user_profile_tab t("account", scope: "layouts.decidim.user_profile"), account_path, aria_link_type: :exact %>
                <%= user_profile_tab t("notifications_settings", scope: "layouts.decidim.user_profile"), notifications_settings_path %>
                <% if available_authorization_handlers.any? %>
                  <%= user_profile_tab t("authorizations", scope: "layouts.decidim.user_profile"), authorizations_path %>
                <% end %>
                <% if user_groups.any? %>
                  <%= user_profile_tab t("user_groups", scope: "layouts.decidim.user_profile"), own_user_groups_path %>
                <% end %>
                <%= user_profile_tab t("delete_my_account", scope: "layouts.decidim.user_profile"), delete_account_path, aria_link_type: :exact %>
              </ul>
            </div>
          </div>
          <div class="columns medium-8 large-9">
            <div class="main-container__content">
              <div class="tabs-content vertical" aria-hidden="false">
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
<% end %>

decidim-core/app/views/layouts/decidim/widget.html.erb
<!DOCTYPE html>
<html class="no-js">
  <head>
    <title><%= decidim_page_title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="widget">
    <% if content_for(:header) == "false" %>
    <% elsif content_for?(:header) %>
      <%= content_for(:header) %>
    <% else %>
      <div class="participatory-process">
        <%= link_to translated_attribute(current_participatory_space.title), resource_locator(current_participatory_space).path, target: "_blank" %>
      </div>
    <% end %>
    <div class="row collapse">
      <div class="column">

        <article class="card">
          <% if current_participatory_space.banner_image %>
            <div class="card__image-top" style="background-image: url(<%= current_participatory_space.banner_image.url %>)"></div>
          <% end %>

          <div class="card__content">
            <div class="card__header">
              <%= link_to model do%>
                <h5 class="card__title"><%= content_for(:title) %></h5>
              <% end %>
              <% if model.try(:author) %>
                <div class="card__author author-data author-data--small">
                  <div class="author-data__main">
                    <div class="author author--inline">
                      <span class="author__avatar author__avatar--small">
                        <%= image_tag model.author_avatar_url %>
                      </span>
                      <span class="author__name"><%= model.author_name %></span>
                      <%= l model.created_at, format: "%d/%m/%Y" %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
            <%= yield %>
          </div>
          <div class="card__footer">
            <% if content_for?(:footer) %>
              <%= content_for(:footer) %>
            <% else %>
              <div class="card__support">
                <div class="card__support__data"></div>
                <%= link_to model, class: "card__button button small", target: "_blank" do %>
                  <%= t('.see_more') %>
                <% end %>
              </div>
            <% end %>
          </div>
        </article>
      </div>
    </div>
    <div class="organization">
      <%= render partial: "layouts/decidim/logo", locals: { organization: current_organization } %>
    </div>

    <%= javascript_include_tag 'decidim/widget' %>
  </body>
</html>